import { useEffect, useMemo, useState } from 'react';
import { Navigate, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { httpsCallable } from 'firebase/functions';
import { onSnapshot, query, where } from 'firebase/firestore';
import { LayoutDashboard, Users, BookOpen, CalendarCheck, WalletCards, UserRound, Settings, LogOut, Menu, X, Plus, Search, ArrowUpRight, ArrowDownRight, Send, Loader2, CheckCircle2 } from 'lucide-react';
import { functions } from './lib/firebase';
import { useAuth } from './context/AuthContext';
import { createRecord, createSchoolForUser, deleteRecord, listenSchool, schoolCollection, updateRecord, watchCollection } from './lib/school';

const NAV=[['/','Dashboard',LayoutDashboard],['/students','Students',Users],['/classes','Classes',BookOpen],['/attendance','Attendance',CalendarCheck],['/fees','Fees & M-Pesa',WalletCards],['/teachers','Teachers',UserRound],['/settings','Settings',Settings]];
const money=n=>`KES ${Number(n||0).toLocaleString('en-KE')}`;
const initials=n=>(n||'School').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();

export default function AppProduction(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/" element={<Guard><Shell/></Guard>}><Route index element={<Dashboard/>}/><Route path="students" element={<Students/>}/><Route path="classes" element={<Classes/>}/><Route path="attendance" element={<Attendance/>}/><Route path="fees" element={<Fees/>}/><Route path="teachers" element={<Teachers/>}/><Route path="settings" element={<SettingsPage/>}/></Route></Routes>}
function Guard({children}){const{user,loading}=useAuth();if(loading)return <Loader/>;return user?children:<Navigate to="/login" replace/>}
function Loader(){return <div className="loading-screen"><div className="loader-orb">S</div><p>Securing your workspace…</p></div>}

function Login(){const{user,loading,signIn,signInGoogle,register,resetPassword}=useAuth();const nav=useNavigate();const[mode,setMode]=useState('signin'),[form,setForm]=useState({name:'',email:'',password:''}),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');useEffect(()=>{if(!loading&&user)nav('/')},[user,loading,nav]);async function submit(e){e.preventDefault();setBusy(true);setNotice('');try{if(mode==='signup')await register(form);else await signIn(form.email,form.password)}catch(e){setNotice(authError(e))}finally{setBusy(false)}}async function google(){setBusy(true);try{await signInGoogle()}catch(e){setNotice(authError(e))}finally{setBusy(false)}}async function forgot(){if(!form.email)return setNotice('Enter your email first.');try{await resetPassword(form.email);setNotice('Password reset email sent.')}catch(e){setNotice(authError(e))}}return <div className="auth-page"><div className="ambient ambient-a"/><div className="ambient ambient-b"/><div className="auth-panel glass"><div className="brand-mark">S</div><span className="eyebrow">SCHOOL OPERATIONS</span><h1>Run your school with clarity.</h1><p className="muted">A secure, lively workspace for students, staff, attendance and fee collection.</p><form onSubmit={submit}>{mode==='signup'&&<Field label="Administrator name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field>}<Field label="Email"><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="admin@school.ac.ke"/></Field><Field label="Password"><input required minLength={6} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/></Field>{mode==='signin'&&<button type="button" className="text-button" onClick={forgot}>Forgot password?</button>}{notice&&<div className={notice.includes('sent')?'success-banner':'alert'}>{notice}</div>}<button className="primary-button full" disabled={busy}>{busy&&<Loader2 size={18} className="spin"/>}{mode==='signin'?'Sign in':'Create account'}</button></form><div className="divider"><span>or</span></div><button className="google-button" disabled={busy} onClick={google}>Continue with Google</button><p className="auth-switch">{mode==='signin'?'New administrator?':'Already registered?'} <button onClick={()=>{setMode(mode==='signin'?'signup':'signin');setNotice('')}}>{mode==='signin'?'Create account':'Sign in'}</button></p></div></div>}

function Shell(){const{user,profile,logout}=useAuth();const[school,setSchool]=useState(null),[mobile,setMobile]=useState(false);const location=useLocation(),nav=useNavigate();useEffect(()=>profile?.schoolId?listenSchool(profile.schoolId,setSchool):undefined,[profile?.schoolId]);if(!profile?.schoolId)return <Onboarding/>;return <div className="app-shell"><aside className={`sidebar glass ${mobile?'open':''}`}><div className="sidebar-brand"><div className="brand-mark small">S</div><div><strong>{school?.name||'Your School'}</strong><span>School OS</span></div><button className="mobile-close" onClick={()=>setMobile(false)}><X size={18}/></button></div><nav>{NAV.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' } onClick={()=>setMobile(false)}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-bottom"><div className="profile-chip"><div className="avatar">{initials(user.displayName||user.email)}</div><div><strong>{user.displayName||'Administrator'}</strong><span>{user.email}</span></div></div><button className="logout" onClick={async()=>{await logout();nav('/login')}}><LogOut size={17}/> Sign out</button></div></aside>{mobile&&<div className="mobile-overlay" onClick={()=>setMobile(false)}/>}<main className="main-area"><header className="topbar glass"><button className="menu-button" onClick={()=>setMobile(true)}><Menu size={21}/></button><div><b>{NAV.find(x=>x[0]===location.pathname)?.[1]||'Workspace'}</b><small>Live school workspace</small></div><div className="sync"><span/> Synced</div></header><div className="content"><RoutesOutlet/></div></main></div>}
function Onboarding(){const{user}=useAuth();const[schoolName,setSchoolName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function create(){if(!schoolName.trim())return setError('Enter your school name.');setBusy(true);try{await createSchoolForUser(user.uid,schoolName)}catch(e){setError(e.message||'Could not create school.')}finally{setBusy(false)}}return <div className="onboarding"><div className="onboarding-card glass"><div className="brand-mark">S</div><span className="eyebrow">WELCOME</span><h1>Create your school workspace.</h1><p className="muted">This creates a private Firestore school space owned by your administrator account.</p><Field label="School name"><input value={schoolName} onChange={e=>setSchoolName(e.target.value)} placeholder="e.g. Baraka Hills Academy"/></Field>{error&&<div className="alert">{error}</div>}<button className="primary-button full" disabled={busy}>{busy&&<Loader2 size={18} className="spin"/>} Create workspace</button></div></div>}
function RoutesOutlet(){return <Routes><Route index element={<Dashboard/>}/><Route path="students" element={<Students/>}/><Route path="classes" element={<Classes/>}/><Route path="attendance" element={<Attendance/>}/><Route path="fees" element={<Fees/>}/><Route path="teachers" element={<Teachers/>}/><Route path="settings" element={<SettingsPage/>}/></Routes>}
function useData(name,sort='createdAt'){const{profile}=useAuth();const[data,setData]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{if(!profile?.schoolId)return;setLoading(true);return watchCollection(profile.schoolId,name,d=>{setData(d);setLoading(false)},sort)},[profile?.schoolId,name,sort]);return[data,loading,profile?.schoolId]}
function Dashboard(){const[students]=useData('students'),[classes]=useData('classes'),[teachers]=useData('teachers'),[payments]=useData('payments','paidAt');const collected=payments.reduce((a,p)=>a+Number(p.amount||0),0);const outstanding=students.reduce((a,s)=>a+Math.max(0,Number(classes.find(c=>c.id===s.classId)?.fee||0)-Number(s.paid||0)),0);return <Page title="Good to see you." subtitle="Your school at a glance."><div className="hero glass"><div><span className="eyebrow">OPERATIONS OVERVIEW</span><h2>Everything in one calm workspace.</h2><p>Real-time records, payment visibility and daily operations in one place.</p></div><div className="hero-orbit"><div>S</div></div></div><div className="stats-grid"><Stat label="Students" value={students.length} icon={Users}/><Stat label="Collected" value={money(collected)} icon={ArrowUpRight}/><Stat label="Outstanding" value={money(outstanding)} icon={ArrowDownRight}/><Stat label="Teachers" value={teachers.length} icon={UserRound}/></div><div className="dashboard-grid"><Card title="Recent payments" action="Open fees" href="/fees">{payments.slice(0,6).map(p=><div className="mini-row" key={p.id}><div><strong>{p.studentName||'Student'}</strong><span>{p.status||'Recorded'}</span></div><b>{money(p.amount)}</b></div>)}{!payments.length&&<Empty text="No payments recorded yet."/>}</Card><Card title="Classes" action="Manage classes" href="/classes">{classes.slice(0,6).map(c=><div className="mini-row" key={c.id}><div><strong>{c.name}</strong><span>{students.filter(s=>s.classId===c.id).length} students</span></div><b>{money(c.fee)}</b></div>)}{!classes.length&&<Empty text="No classes yet."/>}</Card></div></Page>}
function Stat({label,value,icon:Icon}){return <div className="stat-card glass"><div className="stat-icon"><Icon size={18}/></div><span>{label}</span><strong>{value}</strong><small>Live record</small></div>}
function Page({title,subtitle,action,children}){return <div className="page"><div className="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>{children}</div>}
function Card({title,action,href,children}){const nav=useNavigate();return <section className="panel glass"><div className="panel-heading"><h3>{title}</h3>{action&&<button className="text-link" onClick={()=>nav(href)}>{action} →</button>}</div>{children}</section>}
function DataCard({children,loading,grid=false}){return <section className={`panel glass ${grid?'card-grid':''}`}>{loading?<div className="skeleton"/>:children}</section>}
function Empty({text}){return <div className="empty">{text}</div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Modal({title,onClose,onSave,children,saveLabel='Save'}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal glass"><div className="modal-head"><h3>{title}</h3><button className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="modal-body">{children}</div><div className="modal-foot"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={onSave}>{saveLabel}</button></div></div></div>}

function Students(){const[students,loading,schoolId]=useData('students'),[classes]=useData('classes');const[q,setQ]=useState(''),[modal,setModal]=useState(null);const filtered=students.filter(s=>`${s.name} ${s.admissionNo}`.toLowerCase().includes(q.toLowerCase()));return <Page title="Students" subtitle="Enrollment and guardian records." action={<button className="primary-button compact" onClick={()=>setModal({})}><Plus size={16}/> Add student</button>}><Toolbar value={q} onChange={setQ} placeholder="Search name or admission number…"/><DataCard loading={loading}>{filtered.map(s=><div className="list-row" key={s.id}><div className="avatar">{initials(s.name)}</div><div className="row-main"><strong>{s.name}</strong><span>{s.admissionNo} · {classes.find(c=>c.id===s.classId)?.name||'Unassigned'}</span></div><div className="row-meta">{s.guardianPhone||'No guardian phone'}<button className="icon-button" onClick={()=>setModal(s)}>Edit</button><button className="icon-button danger" onClick={()=>remove(schoolId,'students',s.id)}>Delete</button></div></div>)}{!filtered.length&&!loading&&<Empty text="No students found."/>}</DataCard>{modal&&<StudentForm existing={modal.id?modal:null} classes={classes} schoolId={schoolId} close={()=>setModal(null)}/>}</Page>}
function Classes(){const[classes,loading,schoolId]=useData('classes'),[students]=useData('students');const[modal,setModal]=useState(null);return <Page title="Classes" subtitle="Grades, streams and term fees." action={<button className="primary-button compact" onClick={()=>setModal({})}><Plus size={16}/> Add class</button>}><DataCard loading={loading} grid>{classes.map(c=><div className="class-card glass" key={c.id}><div className="class-top"><div><span className="eyebrow">CLASS</span><h3>{c.name}</h3></div><button className="icon-button" onClick={()=>setModal(c)}>Edit</button></div><strong>{money(c.fee)}</strong><span>{students.filter(s=>s.classId===c.id).length} students</span><button className="delete-link" onClick={()=>remove(schoolId,'classes',c.id)}>Remove</button></div>)}{!classes.length&&!loading&&<Empty text="Create your first class."/>}</DataCard>{modal&&<ClassForm existing={modal.id?modal:null} schoolId={schoolId} close={()=>setModal(null)}/>}</Page>}
function Teachers(){const[teachers,loading,schoolId]=useData('teachers'),[classes]=useData('classes');const[modal,setModal]=useState(null);return <Page title="Teachers" subtitle="Teaching staff and class responsibility." action={<button className="primary-button compact" onClick={()=>setModal({})}><Plus size={16}/> Add teacher</button>}><DataCard loading={loading}>{teachers.map(t=><div className="list-row" key={t.id}><div className="avatar">{initials(t.name)}</div><div className="row-main"><strong>{t.name}</strong><span>{t.subject||'General'} · {classes.find(c=>c.id===t.classId)?.name||'No class assigned'}</span></div><div className="row-meta">{t.phone||'No phone'}<button className="icon-button" onClick={()=>setModal(t)}>Edit</button><button className="icon-button danger" onClick={()=>remove(schoolId,'teachers',t.id)}>Delete</button></div></div>)}{!teachers.length&&!loading&&<Empty text="Add your first teacher."/>}</DataCard>{modal&&<TeacherForm existing={modal.id?modal:null} classes={classes} schoolId={schoolId} close={()=>setModal(null)}/>}</Page>}
function Toolbar({value,onChange,placeholder}){return <div className="toolbar glass"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}

function Attendance(){const[students]=useData('students'),[classes]=useData('classes');const{profile}=useAuth();const[classId,setClassId]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[records,setRecords]=useState({});const currentClass=classId||classes[0]?.id;useEffect(()=>{if(!profile?.schoolId||!currentClass)return;const q=query(schoolCollection(profile.schoolId,'attendance'),where('date','==',date),where('classId','==',currentClass));return onSnapshot(q,s=>setRecords(Object.fromEntries(s.docs.map(d=>[d.data().studentId,{id:d.id,...d.data()}]))))},[profile?.schoolId,currentClass,date]);async function mark(studentId,status){const r=records[studentId];if(r)await updateRecord(profile.schoolId,'attendance',r.id,{status});else await createRecord(profile.schoolId,'attendance',{studentId,classId:currentClass,date,status})}const list=students.filter(s=>s.classId===currentClass),present=list.filter(s=>records[s.id]?.status==='present').length,absent=list.filter(s=>records[s.id]?.status==='absent').length;return <Page title="Attendance" subtitle="Daily attendance by class and date."><div className="toolbar glass"><select value={currentClass||''} onChange={e=>setClassId(e.target.value)}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><span className="toolbar-spacer"/><span className="muted">{present} present · {absent} absent</span></div><DataCard>{list.map(s=><div className="attendance-row" key={s.id}><div><strong>{s.name}</strong><span>{s.admissionNo}</span></div><div className="segmented"><button className={records[s.id]?.status==='present'?'selected present':''} onClick={()=>mark(s.id,'present')}>Present</button><button className={records[s.id]?.status==='absent'?'selected absent':''} onClick={()=>mark(s.id,'absent')}>Absent</button></div></div>)}{!list.length&&<Empty text="Add students to this class first."/>}</DataCard></Page>}

function Fees(){const[students,loading]=useData('students'),[classes]=useData('classes'),[payments]=useData('payments','paidAt');const{profile}=useAuth();const[modal,setModal]=useState(null),[q,setQ]=useState(''),[notice,setNotice]=useState('');const collected=payments.reduce((a,p)=>a+Number(p.amount||0),0),filtered=students.filter(s=>`${s.name} ${s.admissionNo}`.toLowerCase().includes(q.toLowerCase()));async function push(data){setNotice('');try{const fn=httpsCallable(functions,'initiateStkPush');const r=await fn({schoolId:profile.schoolId,studentId:data.studentId,phone:data.phone,amount:Number(data.amount),accountReference:data.accountReference||data.studentId,transactionDesc:`School fees - ${data.studentName}`});setNotice(r.data?.message||'STK Push initiated.');setModal(null)}catch(e){setNotice(e.message||'Could not initiate STK Push.')}}return <Page title="Fees & M-Pesa" subtitle="Balances, payment history and secure STK Push requests." action={<button className="primary-button compact" onClick={()=>setModal(null||{})}><Send size={16}/> Request payment</button>}><div className="fee-banner glass"><div><span className="eyebrow">M-PESA</span><h3>Secure STK Push</h3><p>The payment request is created by Firebase Functions, keeping Daraja secrets out of the browser.</p></div><div className="fee-total"><span>Recorded</span><strong>{money(collected)}</strong></div></div>{notice&&<div className="success-banner"><CheckCircle2 size={18}/>{notice}</div>}<Toolbar value={q} onChange={setQ} placeholder="Search students…"/><DataCard loading={loading}>{filtered.map(s=>{const fee=Number(classes.find(c=>c.id===s.classId)?.fee||0),paid=Number(s.paid||0),balance=Math.max(0,fee-paid);return <div className="list-row" key={s.id}><div className="avatar">{initials(s.name)}</div><div className="row-main"><strong>{s.name}</strong><span>{classes.find(c=>c.id===s.classId)?.name||'Unassigned'} · {s.guardianPhone||'No guardian phone'}</span></div><div className="balance"><span>Balance</span><strong>{money(balance)}</strong></div><button className="primary-button compact" onClick={()=>setModal(s)}>Pay</button></div>})}</DataCard>{modal&&<PaymentForm student={modal.id?modal:null} students={students} close={()=>setModal(null)} submit={push}/>}</Page>}
function PaymentForm({student,students,close,submit}){const s=student||students[0], [f,setF]=useState({studentId:s?.id||'',studentName:s?.name||'',phone:s?.guardianPhone||'',amount:'',accountReference:s?.admissionNo||''});return <Modal title="Send M-Pesa STK Push" onClose={close} onSave={()=>submit(f)} saveLabel="Send prompt"><Field label="Student"><select value={f.studentId} onChange={e=>{const n=students.find(x=>x.id===e.target.value);setF({...f,studentId:n.id,studentName:n.name,phone:n.guardianPhone||'',accountReference:n.admissionNo||''})}}>{students.map(x=><option key={x.id} value={x.id}>{x.name} — {x.admissionNo}</option>)}</select></Field><Field label="M-Pesa number"><input required value={f.phone} onChange={e=>setF({...f,phone:e.target.value})} placeholder="2547XXXXXXXX"/></Field><Field label="Amount (KES)"><input required type="number" min="1" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field><Field label="Account reference"><input maxLength={12} value={f.accountReference} onChange={e=>setF({...f,accountReference:e.target.value.toUpperCase()})}/></Field><p className="form-note">The parent must review and authorize the M-Pesa prompt on their phone.</p></Modal>}
function StudentForm({existing,classes,schoolId,close}){const[f,setF]=useState(existing||{name:'',admissionNo:'',classId:classes[0]?.id||'',guardianName:'',guardianPhone:''});async function save(){if(!f.name.trim()||!f.admissionNo.trim())return alert('Name and admission number are required.');if(existing)await updateRecord(schoolId,'students',existing.id,f);else await createRecord(schoolId,'students',{...f,paid:0});close()}return <Modal title={existing?'Edit student':'Add student'} onClose={close} onSave={save}><Field label="Full name"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Admission number"><input value={f.admissionNo} onChange={e=>setF({...f,admissionNo:e.target.value})}/></Field><Field label="Class"><select value={f.classId} onChange={e=>setF({...f,classId:e.target.value})}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Guardian phone"><input value={f.guardianPhone} onChange={e=>setF({...f,guardianPhone:e.target.value})} placeholder="2547XXXXXXXX"/></Field></Modal>}
function ClassForm({existing,schoolId,close}){const[f,setF]=useState(existing||{name:'',fee:''});async function save(){const data={name:f.name.trim(),fee:Number(f.fee||0)};if(!data.name)return alert('Class name is required.');if(existing)await updateRecord(schoolId,'classes',existing.id,data);else await createRecord(schoolId,'classes',data);close()}return <Modal title={existing?'Edit class':'Add class'} onClose={close} onSave={save}><Field label="Class name"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Grade 5 East"/></Field><Field label="Term fee (KES)"><input type="number" min="0" value={f.fee} onChange={e=>setF({...f,fee:e.target.value})}/></Field></Modal>}
function TeacherForm({existing,classes,schoolId,close}){const[f,setF]=useState(existing||{name:'',subject:'',classId:'',phone:''});async function save(){if(!f.name.trim())return alert('Name is required.');if(existing)await updateRecord(schoolId,'teachers',existing.id,f);else await createRecord(schoolId,'teachers',f);close()}return <Modal title={existing?'Edit teacher':'Add teacher'} onClose={close} onSave={save}><Field label="Full name"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Subject"><input value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}/></Field><Field label="Class in charge"><select value={f.classId} onChange={e=>setF({...f,classId:e.target.value})}><option value="">None</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Phone"><input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></Field></Modal>}
function SettingsPage(){const{profile}=useAuth();return <Page title="Settings" subtitle="Workspace, Firebase and production security."><div className="settings-grid"><div className="settings-card glass"><span className="eyebrow">WORKSPACE</span><h3>Private school database</h3><p>Every operational collection lives beneath your school ID, keeping records separated between schools.</p><code>{profile?.schoolId||'No school ID'}</code></div><div className="settings-card glass"><span className="eyebrow">PAYMENTS</span><h3>Daraja backend</h3><p>Credentials belong in Firebase Functions secrets. Never put consumer key, secret or passkey in Vite environment variables.</p><a className="text-link" href="https://developer.safaricom.co.ke/" target="_blank" rel="noreferrer">Open Daraja developer portal →</a></div></div></Page>}
function remove(schoolId,name,id){if(window.confirm('Delete this record?'))deleteRecord(schoolId,name,id)}
function authError(e){const m={'auth/invalid-credential':'Email or password is incorrect.','auth/email-already-in-use':'That email is already registered.','auth/weak-password':'Use a stronger password.','auth/popup-closed-by-user':'Google sign-in was cancelled.'};return m[e?.code]||e?.message||'Authentication failed.'}
